on:
  push:
    branches:
      - master

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        project-root-path: [./serverless]
    steps:
    - uses: actions/checkout@v3
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Register .env
      working-directory: ${{ matrix.project-root-path }}
      env:
        LINE_BOT_CHANNEL_ACCESSTOKEN: ${{ secrets.LINE_BOT_CHANNEL_ACCESSTOKEN }}
        LINE_BOT_CHANNEL_ID: ${{ secrets.LINE_BOT_CHANNEL_ID }}
        LINE_BOT_CHANNEL_SECRET: ${{ secrets.LINE_BOT_CHANNEL_SECRET }}
        LINE_NOTIFY_CLIENT_ID: ${{ secrets.LINE_NOTIFY_CLIENT_ID }}
        LINE_NOTIFY_CLIENT_SECRET: ${{ secrets.LINE_NOTIFY_CLIENT_SECRET }}
      run: |
        echo "LINE_BOT_CHANNEL_ACCESSTOKEN=${LINE_BOT_CHANNEL_ACCESSTOKEN}" >> ./.env
        echo "LINE_BOT_CHANNEL_ID=${LINE_BOT_CHANNEL_ID}" >> ./.env
        echo "LINE_BOT_CHANNEL_SECRET=${LINE_BOT_CHANNEL_SECRET}" >> ./.env
        echo "LINE_NOTIFY_CLIENT_ID=${LINE_NOTIFY_CLIENT_ID}" >> ./.env
        echo "LINE_NOTIFY_CLIENT_SECRET=${LINE_NOTIFY_CLIENT_SECRET}" >> ./.env
    - name: Register firebaseConfig.json
      working-directory: ${{ matrix.project-root-path }}
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: |
        echo "${FIREBASE_CONFIG}" >> ./firebaseConfig.json
    - name: yarn install
      working-directory: ${{ matrix.project-root-path }}
      run: yarn install
    - name: serverless package and deploy
      working-directory: ${{ matrix.project-root-path }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn run serverless package --stage production --package ./build
        yarn run serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        yarn run serverless deploy --stage production --package ./build